name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/deploy.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: cloud-automation-lab-ecr-repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::017367776521:role/cloud-automation-lab-github-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            ./app

      - name: Push Docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Update desired image tag
        run: |
          aws ssm put-parameter \
            --name "/cloud-automation-lab/image-tag" \
            --type "String" \
            --value "${{ github.sha }}" \
            --overwrite

  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: arn:aws:iam::017367776521:role/cloud-automation-lab-github-deploy-role
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Deploy through SSM
  #       run: |
  #         aws ssm send-command \
  #           --document-name "AWS-RunShellScript" \
  #           --targets \
  #             "Key=tag:Project,Values=cloud-automation-lab" \
  #             "Key=tag:Role,Values=app" \
  #           --parameters 'commands=["/usr/local/bin/deploy-app"]'